server:
  servlet:
    context-path: /server-java
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/breakfastapp-server-java
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
