server:
  servlet:
    context-path: /server-java
  port: 8080
spring:
  liquibase:
    enabled: false
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/breakfastapp-server-java
    username: postgres
    password: postgres




