spring:
  profiles: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/breakfastapp-server-java
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    serialization.write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
server:
  port: 8082
---
spring:
  profiles: local
  datasource:
    url: ${JDBC_DATABASE_URL:}
server:
  port: 5000


