spring:
  profiles: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/breakfastapp-server-java
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    serialization.write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
server:
  port: 8082
---
spring:
  profiles: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://wpxvsdikomcdga:9e935dfa40d09d0bc1420c998dc9971d3aab447bdb2dadf1102542919d1e195f@ec2-174-129-226-234.compute-1.amazonaws.com:5432/dcfa1d0hprkfl
server:
  port: 5000


